server:
  port: 8081

rocketmq:
  name-server: 172.31.239.163:9876
  producer:
    group: default

spring:
  datasource:
    url: jdbc:mysql://${db.url:124.223.116.176:3306}/qt_transaction_demo?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
